train_mode: "finetune_tasks"  # "pretrain" or "fine-tune"

training_model_parameters:
    pc_latent_dim: 2048

data_module_parameters:
  data_dir: "./pretrain_data/single_cubby_tasks_135k"
  trajectory_key: 'global_solutions' # Could also use 'global_solutions' for the global expert
  num_obstacle_points: 0
  num_target_points: 0
  random_scale: 0

shared_parameters:
    num_robot_points: 2048

model_path: null #"./checkpoints/sdrwmtfu/last.ckpt"
checkpoint_interval: 10
validation_interval: 1000
accelerator: "gpu"
gpu_num: 1  # If > 1, PyTorch Lightning will automatically use DDP for training
batch_size: 16
save_checkpoint_dir: "./checkpoints"
experiment_name: encoder_pn2_single_cubby_tasks_135k_predict_q
